CREATE TABLE Payments (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL,
    payment_date DATE,
    status varchar(20)
    );

CREATE TABLE Reports (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    from_date DATE,
    to_date DATE
);